(cl:in-package bigcar_nav-msg)
(cl:export '(RECOGNIZE-VAL
          RECOGNIZE
          SHOT-VAL
          SHOT
          GRAB-VAL
          GRAB
          I-VAL
          I
          I_X-VAL
          I_X
          I_Y-VAL
          I_Y
          X_OFFSET-VAL
          X_OFFSET
          Y_OFFSET-VAL
          Y_OFFSET
          TYPE-VAL
          TYPE
          DIRECT-VAL
          DIRECT
          HEIGHT-VAL
          HEIGHT
          ARM_STATUS-VAL
          ARM_STATUS
          CLAW_STATUS-VAL
          CLAW_STATUS
          LIFT_STATUS-VAL
          LIFT_STATUS
          VISION_STATUS-VAL
          VISION_STATUS
          DEPTH-VAL
          DEPTH
          TARGET_NAME-VAL
          TARGET_NAME
          DO_WHAT-VAL
          DO_WHAT
          NAME-VAL
          NAME
))